function BER = runQPSKSystemUnderTest(prmQPSKTxRx, useScopes, printData)

% Copyright 2012-2016 The MathWorks, Inc.

%#codegen 

persistent qpskTx qpskChan qpskRx qpskScopes 
coder.extrinsic('createQPSKScopes','runQPSKScopes','releaseQPSKScopes')
if isempty(qpskTx)
    % Initialize the components
    % Create and configure the transmitter System object
    qpskTx = QPSKTransmitter(...
        'UpsamplingFactor', prmQPSKTxRx.Upsampling, ...
        'MessageLength', prmQPSKTxRx.MessageLength, ...
        'TransmitterFilterCoefficients',prmQPSKTxRx.TransmitterFilterCoefficients, ...
        'DataLength', prmQPSKTxRx.DataLength, ...
        'ScramblerBase', prmQPSKTxRx.ScramblerBase, ...
        'ScramblerPolynomial', prmQPSKTxRx.ScramblerPolynomial, ...
        'ScramblerInitialConditions', prmQPSKTxRx.ScramblerInitialConditions, ...
        'numTx', prmQPSKTxRx.numTx);
    
    % Create and configure the AWGN channel System object
    qpskChan = QPSKChannel('DelayType', prmQPSKTxRx.DelayType, ...
        'RaisedCosineFilterSpan', prmQPSKTxRx.RaisedCosineFilterSpan, ...
        'PhaseOffset', prmQPSKTxRx.PhaseOffset, ...
        'SignalPower', 1/prmQPSKTxRx.Upsampling, ...
        'FrameSize', prmQPSKTxRx.FrameSize, ...
        'UpsamplingFactor', prmQPSKTxRx.Upsampling, ...
        'EbNo', prmQPSKTxRx.EbNo, ...
        'BitsPerSymbol', prmQPSKTxRx.Upsampling/prmQPSKTxRx.Downsampling, ...
        'FrequencyOffset', prmQPSKTxRx.FrequencyOffset, ...
        'SampleRate', prmQPSKTxRx.Fs, ...
        'NumTransmitAntennas',prmQPSKTxRx.numTx, ...
        'NumReceiveAntennas',prmQPSKTxRx.numRx, ...
        'tau',prmQPSKTxRx.tau, ...
        'pdb',prmQPSKTxRx.pdb, ...
        'maxDopp',prmQPSKTxRx.maxDopp, ...
        'H21',prmQPSKTxRx.H21, ...
        'H12',prmQPSKTxRx.H12, ...
        'H22',prmQPSKTxRx.H22);

    % Create and configure the receiver System object
    qpskRx = QPSKReceiver('DesiredAmplitude', 1/sqrt(prmQPSKTxRx.Upsampling), ...
        'ModulationOrder', prmQPSKTxRx.M, ...
        'DownsamplingFactor', prmQPSKTxRx.Downsampling, ...
        'CoarseCompFrequencyResolution', prmQPSKTxRx.CoarseCompFrequencyResolution, ...
        'PhaseRecoveryDampingFactor', prmQPSKTxRx.PhaseRecoveryDampingFactor, ...
        'PhaseRecoveryLoopBandwidth', prmQPSKTxRx.PhaseRecoveryLoopBandwidth, ...
        'TimingRecoveryDampingFactor', prmQPSKTxRx.TimingRecoveryDampingFactor, ...
        'TimingRecoveryLoopBandwidth', prmQPSKTxRx.TimingRecoveryLoopBandwidth, ...
        'TimingErrorDetectorGain', prmQPSKTxRx.TimingErrorDetectorGain, ...
        'PostFilterOversampling', prmQPSKTxRx.Upsampling/prmQPSKTxRx.Downsampling, ...
        'FrameSize', prmQPSKTxRx.FrameSize, ...
        'BarkerLength', prmQPSKTxRx.BarkerLength, ...
        'MessageLength', prmQPSKTxRx.MessageLength, ...
        'SampleRate', prmQPSKTxRx.Fs, ...
        'DataLength', prmQPSKTxRx.DataLength, ...
        'ReceiverFilterCoefficients', prmQPSKTxRx.ReceiverFilterCoefficients, ...
        'DescramblerBase', prmQPSKTxRx.ScramblerBase, ...
        'DescramblerPolynomial', prmQPSKTxRx.ScramblerPolynomial, ...
        'DescramblerInitialConditions', prmQPSKTxRx.ScramblerInitialConditions,...
        'PrintOption', printData, ...
        'numTx', prmQPSKTxRx.numTx, ...
        'numRx', prmQPSKTxRx.numRx, ...
        'H12',prmQPSKTxRx.H12, ...
        'H21',prmQPSKTxRx.H21, ...
        'H22',prmQPSKTxRx.H22);    
    
    if useScopes
        % Create the System object for plotting all the scopes
        qpskScopes = createQPSKScopes;
    end
end

qpskRx.PrintOption = printData;

for count = 1:prmQPSKTxRx.FrameCount
    transmittedSignal = qpskTx(); % Transmitter
    corruptSignal = qpskChan(transmittedSignal, count); % AWGN Channel
    [RCRxSignal,BER] = qpskRx(corruptSignal); % Receiver
    if useScopes
        runQPSKScopes(qpskScopes,RCRxSignal,coarseCompBuffer, timingRecBuffer); % Plots all the scopes
    end
end
if isempty(coder.target)
    release(qpskTx);
    release(qpskChan);
    release(qpskRx);
end
if useScopes
     releaseQPSKScopes(qpskScopes);
end
